name: minimills
description: A grocery shopping application with delivery tracking system.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  postgrest: ^2.4.2
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.4
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  nepali_date_picker: ^7.0.1
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  path: ^1.9.0
  uuid: ^4.5.1
  intl: ^0.20.2
  app_links: ^6.4.0
  google_maps_flutter: ^2.13.1
  geocoding: ^4.0.0
  latlong2: ^0.9.1
  weather: ^3.2.1
  radio_group_v2: ^3.3.1
  http: ^1.6.0
  flutter_polyline_points: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/minimills_logo.png